#Vagrant.require_plugin "vagrant-windows"

Vagrant.configure("2") do |config|
  config.vm.box = "win7x64pro"

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07NE00OEQyYnoySDg/"
    v.gui = true
    #v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07WW1LamJzakt2MUE/"
    v.gui = true
    #v.vmw["custom-key"] = "value"
  end

  config.vm.guest = :windows
  config.windows.halt_timeout = 20
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network :forwarded_port, guest: 5985, host: 5985 #WinRM


  config.vm.synced_folder "~", "/home"
  #config.vm.synced_folder "resources/templates/_templates", "/code/_templates"
  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

  # This shell provisioner installs chocolatey, ruby, and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "shell/main.cmd"

  # config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
  #   puppet.manifests_path = "puppet/manifests"
  #   puppet.manifest_file  = "site.pp"
  #   puppet.module_path = "puppet/modules"
  #   puppet.facter = {
  #     "domain" => "local",
  #     "kernel" => "windows",
  #     "operatingsystem" => "windows",
  #     "osfamily" => "windows",
  #   }
  # end
end
