#Vagrant.require_plugin "vagrant-windows"

Vagrant.configure("2") do |config|
  config.vm.box = "win2012r2x64"

  config.vm.provider :virtualbox do |v, override|
    #override.vm.box_url = "URL_HERE"
    v.gui = true
    #v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # Use VBoxManage to customize the VM. For example to change memory:
    #v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.guest = :windows
  config.windows.halt_timeout = 20
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.synced_folder "~", "/home"
  #config.vm.synced_folder "resources/templates/_templates", "/code/_templates"

  # This shell provisioner installs chocolatey and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "shell/main.cmd"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "provision.pp"
    puppet.module_path = "puppet/modules"
    # puppet.facter = {
    #   "domain" => "local",
    #   "kernel" => "windows",
    #   "operatingsystem" => "windows",
    #   "osfamily" => "windows",
    # }
  end
end
